@ECHO OFF
ECHO Start ...

ECHO Compiling index.html ...
php source/index.php > compiled/index.html

ECHO Compiling services.html ...
php source/services.php > compiled/services.html

ECHO Compiling about.html ...
php source/about.php > compiled/about.html

ECHO Compiling contact.html ...
php source/contact.php > compiled/contact.html

ECHO Compiling portfolio/portfolio-1-col.html ...
php source/portfolio/portfolio-1-col.php > compiled/portfolio/portfolio-1-col.html

ECHO Compiling portfolio/portfolio-2-col.html ...
php source/portfolio/portfolio-2-col.php > compiled/portfolio/portfolio-2-col.html

ECHO Compiling portfolio/portfolio-3-col.html ...
php source/portfolio/portfolio-3-col.php > compiled/portfolio/portfolio-3-col.html

ECHO Compiling portfolio/portfolio-4-col.html ...
php source/portfolio/portfolio-4-col.php > compiled/portfolio/portfolio-4-col.html

ECHO Compiling portfolio/portfolio-single.html ...
php source/portfolio/portfolio-single.php > compiled/portfolio/portfolio-single.html

ECHO Finished ...
pause