@ECHO OFF
ECHO Start ...

ECHO Setup directories if needed ...
if not exist "compiled" mkdir compiled
cd compiled
if not exist "assets" mkdir assets
cd ..

ECHO Compiling index.html ...
php source/index.php > compiled/index.html

ECHO Compiling services.html ...
php source/services.php > compiled/services.html

ECHO Compiling about.html ...
php source/about.php > compiled/about.html

ECHO Compiling contact.html ...
php source/contact.php > compiled/contact.html

ECHO Compiling portfolio-1-col.html ...
php source/portfolio-1-col.php > compiled/portfolio-1-col.html

ECHO Compiling portfolio-2-col.html ...
php source/portfolio-2-col.php > compiled/portfolio-2-col.html

ECHO Compiling portfolio-3-col.html ...
php source/portfolio-3-col.php > compiled/portfolio-3-col.html

ECHO Compiling portfolio-4-col.html ...
php source/portfolio-4-col.php > compiled/portfolio-4-col.html

ECHO Compiling portfolio-single.html ...
php source/portfolio-single.php > compiled/portfolio-single.html

ECHO Finished ...
pause